version: '3.9'

services:
  redis:
    image: redis:6.0.10
    networks:
      sentry:  

  postgres:
    image: postgres:12.5
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
    volumes:
     - postgres:/var/lib/postgresql/data
    networks:
      sentry:  
  
  sentry:
    image: sentry:9.1.2
    ports:
     - 9991:9000
    env_file:
      - sentry-variables.env
    networks:
      sentry:  
  
  sentry-cron:
    image: sentry:9.1.2
    command: "sentry run cron"
    env_file:
      - sentry-variables.env
    networks:
      sentry:  
  
  sentry-worker-1:
    image: sentry:9.1.2
    command: "sentry run worker"
    env_file:
      - sentry-variables.env
    networks:
      sentry:  

networks:
  sentry:
